### ISSUE TITLE
Fix the loading problem

### ISSUE THREAD

**Issue by ztoolson** [mxenabled/atrium-ruby#13]
When adding "atrium-ruby" to the Gemfile, atrium doesn't get loaded. I used a workaround of

`gem 'atrium-ruby', require: 'atrium'`, but that is bad. We should just fix this.

**Comment by ztoolson** [comment]
Also we should probably just call the gem mx-atrium

**Comment by vintagepenguin** [comment]
yeah @ztoolson I'm up for calling it `mx-atrium`...Also let's fix the require part as well

**Comment by film42** [comment]
I think you could also add an `atrium/ruby.rb` file and require the project in from there. I think that would work.
