### ISSUE TITLE
Pagination Options not working

### ISSUE THREAD

**Issue by ztoolson** [mxenabled/atrium-ruby#18]
I'm trying to use the pagination options but they don't seem to be working.

```
irb(main):005:0> ::Atrium::Institution.list(limit: 2).size
=> 15
```

I would expect using the limit to only return 2 institutions. based on the limit. It also looks like the `page` option in query_params is not working either.

**Comment by ztoolson** [comment]
If I specify the page to a page that shouldn't have any institutions, we still return data.

**Comment by ldrbrandon** [comment]
I'm trying to use the Institutions.list method and am always getting errors. 
Here are the following commands and the things they return

`Atrium::Institution.list(query_params: 'chase', limit: 2)` => 
`NoMethodError: undefined method `map' for "chase":String`

`Atrium::Institution.list(query_params: ['chase'], limit: 100)` =>
`SocketError: getaddrinfo: nodename nor servname provided, or not known (vestibule.mx.cominstitutions:443)`

it looks like the base_url is correct but there is no `/` between the domain and the path.

Any chance of a fix?

**Comment by ztoolson** [comment]
I'll take a look. Thanks for the info @ldrbrandon

**Comment by ztoolson** [comment]
@ldrbrandon The query params are expected to be in the format `query_params: { value: query }`. So if you are searching for `chase`, it would be:

```
::Atrium::Institution.list(query_params: {name: 'chase'})
```

The limit size is still an error. I'll put up a fix for that.
