### ISSUE TITLE
Update Harvey Gem API

### ISSUE THREAD

**Issue by ztoolson** [mxenabled/atrium-ruby#2]
This list uses the following conventions: .class_method, #instance_method. Currently the gem has a lot of helper class methods. This propses that we use Ruby objects to wrap the API calls.

Users
=====

- [x] .create `// ::Atrium::User.create({:first_name => "dan", :last_name => "jones"})`
- [x] .list `// ::Atrium::User.list`
- [x] .read `// ::Atrium::User.read("user_guid")`
- [x] #update `// u = ::Atrium::User.read("user_guid"); u.update({:first_name => "zach"})`
- [x] #delete `// u = ::Atrium::User.read("user_guid"); u.delete`
- [x] #accounts `// u = ::Atrium::User.read("user_guid"); u.accounts`
- [ ] #read_account(:account_guid)
- [x] #transactions
- [ ] #read_transaction(:transaction_guid) 
- [x] #members
- [ ] #read_member("member_guid")

`TODO: user connect widget`

Members
=======
- [x] .list
- [x] .create
- [x] .read
- [x] #aggregate
- [x] #resume
- [x] #status
- [x] #challenges
- [x] #update
- [x] #delete
- [x] #accounts
- [x] #read_account(:account_guid)
- [x]  #transactions

Accounts
========
- [x] .list
- [x] .read
- [x]  #transactions

Transactions
============
- [x] .list
- [x] .read

Institutions
============
.list

Credentials
===========
.read

**Comment by ztoolson** [comment]
//cc @vintagepenguin

**Comment by vintagepenguin** [comment]
Gems to Add: 
==========

* `ActiveModel:` https://rubygems.org/gems/activemodel/versions/4.2.6
* `ActiveAttr:`  https://github.com/cgriego/active_attr

Let's include the following to make these objects: 
```
  include ::ActiveAttr::Model
  include ::ActiveAttr::Attributes
```

**Comment by vintagepenguin** [comment]
Parsing Response
=============

 `::JSON.parse(response_body)`

**Comment by jjcarstens** [comment]
@vintagepenguin Just FYI, `include ::ActiveAttr::Model` is a shortcut to include a lot of active_attr functionalities, including `::ActiveAttr::Attributes`, so you shouldn't need to make that second `include`:

http://www.rubydoc.info/gems/active_attr/ActiveAttr/Model
