### ISSUE TITLE
Full support of Institution Model

### ISSUE THREAD

**Issue by jpotts18** [mxenabled/atrium-ruby#33]
Support for **medium_logo_url**, and **small_logo_url** don't seem to be in the Institutions. https://github.com/mxenabled/atrium-ruby/blob/master/lib/atrium/institution.rb#L6

From Docs
https://atrium.mx.com/documentation#institution-fields

Field Name | Data Type | Description
-- | -- | --
code | string | Unique identifier for the institution. Defined by MX.
medium_logo_url | string | URL to get the medium sized logo for this institution. Institutions that don't have a medium logo will have a generic logo returned. Medium logos are 100px by 100px.
name | string | Name of the institution. (Chase Bank).
small_logo_url | string | URL to get the small sized logo for this institution. Institutions that don't have a small logo will have a generic logo returned. Small logos are 50px by 50px.
url | string | The url of the institution. ( https://www.chase.com )

**Comment by film42** [comment]
Released fix in `v0.4.3`.
