### ISSUE TITLE
View helper method to build credentials form?

### ISSUE THREAD

**Issue by jpotts18** [mxenabled/atrium-ruby#34]
I would love see an example of how to build a rails form that appropriately handles the different credential combinations that can come back from institutions.

I'm concerned my form might not be able to handle all of the different possibilities across 30k institution credentials.

### Current Version
```ruby
h2 Login to Institution
= form_tag('/somewhere')
    - @credentials.each do |c|
      .form-group
        = label_tag c.field_name, c.label
        = hidden_field_tag(c.guid)
        - if c.type == "PASSWORD"
          = password_field_tag(c.field_name, c.value, class: 'form-control')
        - else
          = text_field_tag(c.field_name, c.value, class: 'form-control')
    p = submit_tag("Login to Institution", class: 'btn btn-primary btn-block')
```

### Improved Version
```ruby
Atrium::credentials_form_helper(@credentials)
```

**Comment by film42** [comment]
This would be a very helpful example. For now, though, I can at least help by listing our credential type enum:
```protobuf
enum CredentialType {
  TEXT              = 0;
  PASSWORD          = 1;
  OPTIONS           = 2;
  LOGIN             = 3;
  CHECKBOX          = 4;
  RADIO             = 5;
  URL               = 6;
  HIDDEN            = 7;
  IMAGE_URL         = 8;
  CONTENT_URL       = 9;
  CUSTOM            = 10;
  CLUDGE            = 11;
  TOKEN             = 12;
  IMAGE_DATA        = 13;
  IMAGE_OPTIONS     = 14;
}
```

It's rare we see anything other than login, password and options (for MFA). We have some credentials with "TEXT" but I think we need to migrate those over to "LOGIN". Even so, "TEXT" and "LOGIN" are very similar. Image verification is even more rare.

**Comment by jpotts18** [comment]
I ended up using the MX Connect Widget instead.
