### ISSUE TITLE
Listing members returns `true` or `false` for guid

### ISSUE THREAD

**Issue by jscho13** [mxenabled/atrium-ruby#59]
For Atrium version 2.1.0 listing members returns a true or false. I believe this is incorrect since the MBR_GUID should be a string.

Reference here: https://github.com/mxenabled/atrium-ruby/blob/master/lib/atrium-ruby/models/member.rb#L57

**Comment by brettmortensen** [comment]
@jscho13 Thank you for pointing this out 👍 

You are correct - the member guid field should be a string, not a boolean. It appears a typo snuck in during the update to our latest major version.

This has been corrected here: https://github.com/mxenabled/atrium-ruby/commit/ecc0a991466de78ee3306bbbe834c092935f241e

**Comment by jscho13** [comment]
Thanks @brettmortensen. Think you'd be able to assist with this request as well: https://github.com/mxenabled/atrium-ruby/issues/60
