### ISSUE TITLE
Allow Typhoeus Requests to be sent via Proxy

### ISSUE THREAD

**Issue by jscho13** [mxenabled/atrium-ruby#60]
I am sending my `atrium-ruby` requests via a proxy. Right now this isn't configurable (or at least isn't stated in documentation). Instead, I needed to create a local copy of your gem and patch it from there.

This is what worked for me:
```
atrium-ruby-2.1.0/lib/atrium-ruby/api_client.rb
 98       req_opts = {
 99         :method => http_method,
100         :headers => header_params,
101         :params => query_params,
102         :params_encoding => @config.params_encoding,
103         :timeout => @config.timeout,
104         :ssl_verifypeer => @config.verify_ssl,
105         :ssl_verifyhost => _verify_ssl_host,
106         :sslcert => @config.cert_file,
107         :sslkey => @config.key_file,
108         :verbose => @config.debugging,
109         :proxy => ENV['PROXY_URL_HERE']
110       }
```

**Comment by jscho13** [comment]
To be honest I don't know enough on the advantages of one over the other.

I leave it up to you guys on what would make the most sense to implement. This was merely a suggestion.

**Comment by liveh2o** [comment]
Cool. I'll make a config option to keep things consistent.
