### ISSUE TITLE
Can't create any user

### ISSUE THREAD

**Issue by andresviviani1** [mxenabled/atrium-ruby#63]
Hello, 

I'm working with this gem and I'm not able to create any user. I can list them, but when I try to create one, I get: 

> `
ETHON: performed EASY effective_url=https://vestibule.mx.com/users response_code=400 return_code=ok total_time=0.102082
Traceback (most recent call last):
       11: from bin/rails:4:in `<main>'
       10: from bin/rails:4:in `require'
        9: from /Users/andres/.rvm/gems/ruby-2.5.1@sfc_spa/gems/railties-5.0.6/lib/rails/commands.rb:18:in `<top (required)>'
        8: from /Users/andres/.rvm/gems/ruby-2.5.1@sfc_spa/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        7: from /Users/andres/.rvm/gems/ruby-2.5.1@sfc_spa/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:78:in `console'
        6: from /Users/andres/.rvm/gems/ruby-2.5.1@sfc_spa/gems/railties-5.0.6/lib/rails/commands/console_helper.rb:9:in `start'
        5: from /Users/andres/.rvm/gems/ruby-2.5.1@sfc_spa/gems/railties-5.0.6/lib/rails/commands/console.rb:65:in `start'
        4: from (irb):66
        3: from /Users/andres/.rvm/gems/ruby-2.5.1@sfc_spa/gems/atrium-ruby-2.5.0/lib/atrium-ruby/api/users_api.rb:24:in `create_user'
        2: from /Users/andres/.rvm/gems/ruby-2.5.1@sfc_spa/gems/atrium-ruby-2.5.0/lib/atrium-ruby/api/users_api.rb:105:in `create_user_with_http_info'
        1: from /Users/andres/.rvm/gems/ruby-2.5.1@sfc_spa/gems/atrium-ruby-2.5.0/lib/atrium-ruby/api_client.rb:61:in `call_api'
Atrium::ApiError (Bad Request)
`

Any idea why this is happening only for creation? Same thing with member creation.

**Comment by brettmortensen** [comment]
Hi @andresviviani1 

Could you provide us with code snippets of how you are creating a user and member?

The following snippet should work to create a user. (You will need to put in your specific API Key and Client ID)

```
# load the gem
require 'atrium-ruby'

client = Atrium::AtriumClient.new("YOUR API KEY", "YOUR CLIENT ID")

body = Atrium::UserCreateRequestBody.new(
  :user => Atrium::User.new(
    :metadata => "test metadata"
  )
) # UserCreateRequestBody | User object to be created with optional parameters (identifier, is_disabled, metadata)

begin
  #Create user
  response = client.users.create_user(body)
  p response
rescue Atrium::ApiError => e
  puts "Exception when calling UsersApi->create_user: #{e}"
end

```

**Comment by andresviviani1** [comment]
Thanks a lot @brettmortensen ! That works. 

I missed this:
`
:user => Atrium::User.new(
    :metadata => "test metadata"
  )
`

In the snippet here https://atrium.mx.com/docs?ruby#users it is not clear, which is the same as github. Or maybe I misunderstood the comment there.

Thanks again!

**Comment by brettmortensen** [comment]
No problem. Thanks for reaching out 👍
