### ISSUE TITLE
Test users for all scenarios

### ISSUE THREAD

**Issue by andresviviani1** [mxenabled/atrium-ruby#64]
Hello!

I've been reading the official docs and I see only this set of test users: 
https://atrium.mx.com/docs/getting_started#testing-your-setup

However, I read that there are **20+** member connection statuses (https://atrium.mx.com/docs#read-member-connection-status)

I'm not sure if this is the right place to ask for it, but since this is the official site for the ruby wrapper I'm doing it. Do you have any test users to get those statuses when retrieving connection status for a member?

Thank you so much in advance!

**Comment by brettmortensen** [comment]
Hi @andresviviani1 

As you've mentioned, we only have a handful of connection statuses covered by the test users in the docs.

We are working towards building out this functionality and currently have an undocumented way to retrieve a specific member status from this endpoint.

Pass `"test_atrium"` as the user guid and your desired `"connection_status"` as the member guid. Here is a small example of how to get the `DELAYED` status.

```
# load the gem
require 'atrium-ruby'

client = Atrium::AtriumClient.new("YOUR_API_KEY", "YOUR_CLIENT_ID")

member_guid = "MBR-123" # String | The unique identifier for a `member`.
user_guid = "USR-123" # String | The unique identifier for a `user`.

begin
  #Read member connection status
  response = client.members.read_member_status("delayed", "test_atrium")
  p response
rescue Atrium::ApiError => e
  puts "Exception when calling MembersApi->read_member_status: #{e}"
end
```

**Comment by andresviviani1** [comment]
Thank you so much @brettmortensen 

I appreciate it.
