### ISSUE TITLE
Warning: URI.escape is obsolete

### ISSUE THREAD

**Issue by stephenarifin** [mxenabled/atrium-ruby#78]
As of Ruby 2.7, URI.escape is obsolete. We are receiving these warnings from the gem:

```
.rvm/gems/ruby-2.7.3/gems/atrium-ruby-2.10.4/lib/atrium-ruby/configuration.rb:177: warning: URI.escape is obsolete
21:54:23 web.1        | 
.rvm/gems/ruby-2.7.3/gems/atrium-ruby-2.10.4/lib/atrium-ruby/api_client.rb:264: warning: URI.escape is obsolete

```
Can you let us know when this is fixed?

**Comment by brettmortensen** [comment]
Hi @stephenarifin! Thank you for bringing this to our attention.

This has been fixed in https://github.com/mxenabled/atrium-ruby/pull/79 and released as version `2.10.5`.
